file_name = "trainer.voc"

words = {
    "studijny plan": "curriculum",
    "internat": "dormitory",
    "riadny student": "full-time student",
    "absolvent": "graduate",
    "promocia": "graduation ceremony",
    "prednaskova miestnost": "lecture hall",
    "prednasat o": "lecture on",
    "mimoriadny student": "part-time student",
    "studovna": "self-study room",
    "sylaby": "syllabus",
    "akademicky titul": "academic degree",
    "vysokoskolak": "undergraduate",
    "sposob myslenia": "mindset",
    "dosiahnut": "aquire",
    "chodit na prednasky": "attend a lecture",
    "pozostavat z": "consist of",
    "urobit diplomovu pracu na": "do a diploma project on",
    "neurobit skusku": "fail an exam",
    "sustredit sa na": "focus on",
    "ziskat kredit za": "get a credit for",
    "ziskat titul v": "get a degree in",
    "promovat z": "graduate from",
    "ziskat": "obtain",
    "spravit skusku": "pass an exam",
    "spoliehat sa na": "rely on",
    "opakovat na": "revise for",
    "specializovat sa na": "specialise in",
    "absolvovat kurz": "take a course in",
    "ist na skusku": "take an exam",
    "podstupit": "undergo",
    "prikyvnut hlavou": "nod a head",
    "byt pochvaleny": "be praised",
    "postoj": "attitude",
    "zacat byt podrazdeny": "became irritated",
    "prasklo": "snapped",
    "zhrnutie": "digest",
    "znak pozornosti": "sign of affection",
    "pripustny": "permissible",
    "lakat": "beckoning",
    "mozno povazovat za urazku": "can be seen as an insult",
    "silne uchyty": "strong grips",
    "sediet s prekrizenymi nohami": "sit cross-legged",
    "prevladajuci zvyk": "prevailing custom",
    "podrazka tvojej topanky": "sole of your shoe",
    "predsudok": "prejudice",
    "pred": "prior to",
    "nasadit": "put on",
    "prepustit niekoho": "put somebody through",
    "lutovat": "regret",
    "uhrada": "reimbursement",
    "ziadost": "request",
    "nadradeny": "superior",
    "ustredna": "switchboard",
    "ukoncit": "terminate",
    "vyuzit": "utilize",
    "vasnivy": "passionate",
    "pre nic": "it is all for nothing",
    "priemerny prezenter": "mediocre presenter",
    "drzat sa spat": "hold back",
    "publikum": "audience",
    "bludit": "ramble",
    "rozsah pozornosti": "attention spans",
    "budovanie vztahu": "build rapport",
    "ovladac": "handheld remote",
    "dostat vypadok": "go blank",
    "prejst z temy": "move off the topic",
    "znovuobjavenie obrazku": "image reappears",
    "pohlad nadol": "glance down",
    "drzat ocny kontakt": "mantain eye contact",
    "pocmurna tema": "grim topic",
    "pokusenie": "temptation",
    "uviest komentare": "give comments",
    "laskave": "gracious",
    "drzat sa na vrchole": "keep to the high ground",
    "narocne publikum": "challenging audience"
}
